cmake: Don't build 32 bit binaries for VkLayer_khronos_shader_object
KhronosGroup/Vulkan-ExtensionLayer pull request #191
Opened 2023-04-13 22:08 UTC by juan-lunarg

2023-04-13 22:14 UTC, lunarpapillo commented on layers/CMakeLists.txt
> +if (NOT WIN32)
Isn't this backwards?  should be `if(WIN32)`, not `if(NOT WIN32)`, right?

2023-04-13 22:16 UTC, lunarpapillo requested changes
You caught the logic inversion on `if (NOT WIN32)` before I could report it. :-)

One comment addition, then consider it approved by me.

2023-04-13 22:16 UTC, lunarpapillo commented on layers/CMakeLists.txt
> +if (CMAKE_SIZEOF_VOID_P EQUAL "4")
This is unusual, so a comment saying that the Vulkan SDK has deliberately chosen not to ship 32-bit `VkLayer_khronos_shader_object` files would save confusion in the future.

2023-04-14 16:10 UTC, juan-lunarg commented
64 bit Windows installation:
```
-- Installing: D:/a/Vulkan-ExtensionLayer/Vulkan-ExtensionLayer/build/./install/lib/VkLayer_khronos_synchronization2.json
-- Installing: D:/a/Vulkan-ExtensionLayer/Vulkan-ExtensionLayer/build/./install/lib/VkLayer_khronos_synchronization2.dll
-- Installing: D:/a/Vulkan-ExtensionLayer/Vulkan-ExtensionLayer/build/./install/lib/VkLayer_khronos_shader_object.json
-- Installing: D:/a/Vulkan-ExtensionLayer/Vulkan-ExtensionLayer/build/./install/lib/VkLayer_khronos_shader_object.dll
```

32 bit Windows installation:
```
-- Installing: D:/a/Vulkan-ExtensionLayer/Vulkan-ExtensionLayer/build/./install/lib/VkLayer_khronos_synchronization2.json
-- Installing: D:/a/Vulkan-ExtensionLayer/Vulkan-ExtensionLayer/build/./install/lib/VkLayer_khronos_synchronization2.dll
```

@lunarpapillo I think this is good to go now.

2023-04-14 18:04 UTC, jeremyg-lunarg commented
@juan-lunarg do you still want this PR?

2023-04-14 18:05 UTC, juan-lunarg commented
Yes we still need this PR for the Windows SDK release

2023-04-14 19:45 UTC, jeremyg-lunarg approved these changes
LGTM

2023-04-14 19:51 UTC, merged