docs: Update README.md to include layer Point of Contacts
KhronosGroup/Vulkan-ExtensionLayer pull request #198
Opened 2023-04-18 15:13 UTC by jeremyg-lunarg

Now that there are multiple layers in this repo that are actively used, we need to make sure the people who understand each layer are documented and tagged on any Issues.

2023-04-18 15:20 UTC, KarenGhavam-lunarG commented
@jeremyg-lunarg I believe we should get the github handle for the contributor of the timeline semaphore layer and add them to the contacts. And then create an issue assigned to that individual that they should add a document describing the purpose of the layer, similar to what exists for the sync2 and shader object layer.

2023-04-18 15:33 UTC, KarenGhavam-lunarG requested changes
@jeremyg-lunarg I believe we should get the github handle for the contributor of the timeline semaphore layer and add them to the contacts. And then create an issue assigned to that individual that they should add a document describing the purpose of the layer, similar to what exists for the sync2 and shader object layer.

2023-04-18 16:00 UTC, jeremyg-lunarg commented
@llandwerlin-intel , are you OK being listed as a Point of Contact for VK_LAYER_khronos_timeline_semaphore?  It has had very little activity over the last couple of years but at least [one person](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/118) is still using on Android.

2023-04-18 18:57 UTC, llandwerlin-intel commented
> @llandwerlin-intel , are you OK being listed as a Point of Contact for VK_LAYER_khronos_timeline_semaphore? It has had very little activity over the last couple of years but at least [one person](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/118) is still using on Android.

Not sure I would be able to do any work on it. But if there is no one else, sure.

2023-04-18 20:19 UTC, jeremyg-lunarg commented
> > @llandwerlin-intel , are you OK being listed as a Point of Contact for VK_LAYER_khronos_timeline_semaphore? It has had very little activity over the last couple of years but at least [one person](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/118) is still using on Android.
> 
> Not sure I would be able to do any work on it. But if there is no one else, sure.

Thank you. We ought to be able to handle build problems like the one I linked. We don't include this layer in the Vulkan SDK, so I really hope it continues to not need much attention.

2023-04-19 17:43 UTC, KarenGhavam-lunarG reviewed
Only one small grammar change, but the rest looks good.

2023-04-19 17:43 UTC, KarenGhavam-lunarG commented on CONTRIBUTING.md
> +The Point of Contact handle Issues reported against the layer, as the repository maintainers most
The Point of Contact handles issues reported against the layer, ...

2023-04-19 20:27 UTC, KarenGhavam-lunarG approved these changes

2023-04-19 20:27 UTC, merged