shaderObject: Fix creating shaders with incompatible binary
KhronosGroup/Vulkan-ExtensionLayer pull request #211
Opened 2023-05-06 10:03 UTC by ziga-lunarg

Make sure the correct VkResult is returned

2023-05-08 15:06 UTC, jeremyg-lunarg requested changes

2023-05-08 15:06 UTC, jeremyg-lunarg commented on layers/shader_object.cpp
> +    bool incompatibleBinary = false;
this variable should be snake_case

2023-05-08 15:57 UTC, jeremyg-lunarg approved these changes
LGTM, I'll let you merge this when you're sure it is ready.

2023-05-11 21:46 UTC, jeremyg-lunarg commented
please rebase to pick up CI fixes

2023-07-12 21:12 UTC, daniel-story approved these changes

2023-07-13 13:34 UTC, merged