tests: Add portability extension for sync2 tests
KhronosGroup/Vulkan-ExtensionLayer pull request #335
Opened 2023-10-30 21:34 UTC by richard-lunarg

One of the sync2 tests had failed to account for the portability enumeration extension when running on Apple platforms. This PR corrects that.

2023-10-30 21:37 UTC, ziga-lunarg approved these changes

2023-10-31 14:01 UTC, jeremyg-lunarg requested changes
The current version of this PR deletes all the sync2 tests. Why?

2023-10-31 14:48 UTC, richard-lunarg commented
That's a mistake....

2023-10-31 14:48 UTC, closed without merging

2023-10-31 16:24 UTC, jeremyg-lunarg commented
> That's a mistake....

Looks like you could just use `git rebase -i` to remove the last commit